#!/bin/sh
#
# addcol - add columns to a table
#
# Usage: addcol columns < data
#
# Author: gunnar@hafro.is
#
# NOTE: This seems to generate an invalid table -- extra tabs
#       should be added in the data part.
#    jpn fixed 1-24-90

add=
for i 
do
	add=$add'	'$i
	addtabs=$addtabs'	'
done
sed '1{
s/$/'"$add"'/
p
s/[^	]/-/g
}
2d
3,$s/$/'"$addtabs"'/
' 
