#' @title XXX
#' 
#' @export
#' 
#' @param mat XXX
#' @param fullmat XXX
#' @param add XXX

add.to.matrix <- 
  function(mat, fullmat, add = F)
  {
    tmpmat <- matrix(0., nrow(mat), ncol(fullmat))
    i <- match(dimnames(mat)[[2.]], dimnames(fullmat)[[2.]])
    tmpmat[, i] <- mat
    dimnames(tmpmat) <- list(dimnames(mat)[[1.]], dimnames(fullmat)[[2.]])
    i <- match(dimnames(tmpmat)[[1.]], dimnames(fullmat)[[1.]])
    if(add)
      fullmat[i,  ] <- fullmat[i,  ] + tmpmat
    else fullmat[i,  ] <- tmpmat
    return(fullmat)
  }
#' @title XXX
#' 
#' @description XXX
#' 
#' @export
#' 
#' @param dat XXX
#' @param gear XXX
#' @param Land.gear XXX
#' @param area XXX
#' @param month XXX

catch_by_month_and_bormicon <- function(dat,gear,Land.gear,area=c(1:10),month=c(1:12)) {
  
  tmp <- matrix(0,length(month),length(area))
  dimnames(tmp) <- list(month,area)
  
  i <- dat$area %in% area & dat$veman %in% month & dat$veidarf %in% gear

  res <- tapply(dat[,4][i],list(dat$area[i],dat$veman[i]),sum)
  res[is.na(res)] <- 0
  res <- add.to.matrix(t(res),tmp)
  res <- round(res*Land.gear[as.character(gear)]/sum(res))
  return(res)
}

#' @title XXX
#' 
#' @description XXX
#' 
#' @export
#' 
#' @param metier A character specifying the metier fro which to calculate catch at age.
#' @param catch A value, the total catch in the metier
#' @param stations A data.table containing station information
#' @param ages A data.table containing age readings
#' @param lengths A data.table containing length distributions
#' @param cond XXX
#' @param LE XXX
#' @param ALDUR XX
#' @param weight1 A value between 0 and 1. The weight in the alk given to otoliths from
#' other metiers within the regiona and time period. This shitmix can be turned
#' by setting value to zero.
#' @param weight2 A value between 0 and 1. The weight in the alk given to all otoliths
#' sampled in the year (including surveys). This shitmix can be turned
#' by setting value to zero.

calc_catch_at_age_by_metier <- function(metier,catch,
                                        stations,ages,lengths,
                                        cond,LE,ALDUR,weight1=0.01,weight2=0.0001)
{
  
  # dummy, just to pass R CMD check (always happens when using ddply)
  synis.id <- fjoldi <- NULL
  
  gear  <- as.integer(substr(metier,2,2))
  area  <- as.integer(substr(metier,4,4))
  period <- as.integer(substr(metier,6,6))

  # Get data
  st <- stations[stations$index %in% metier,]
  ag <- ages[!is.na(match(ages$synis.id,st$synis.id)),]
  le <- lengths[!is.na(match(lengths$synis.id,st$synis.id)),]
  
  # Compile sample informations
  info <- plyr::ddply(st,"synaflokkur",summarise,samples=length(synis.id))
  if(nrow(info) == 0) info <- data.frame(synaflokkur=NA,samples=0) 
  
  if(nrow(ag) > 0) {
    x <- plyr::join(ag[,c("synis.id","fjoldi")],st[,c("synis.id","synaflokkur")],by="synis.id")
    x <- plyr::ddply(x,"synaflokkur",summarise,n.ages=sum(fjoldi,na.rm=T))
    info <- plyr::join(info,x,by="synaflokkur")
  } else {
    info$n.ages <- 0
  }
  
  if(nrow(le) > 0) {
    x <- plyr::join(le[,c("synis.id","fjoldi")],st[,c("synis.id","synaflokkur")],by="synis.id")
    x <- plyr::ddply(x,"synaflokkur",summarise,n.lengths=sum(fjoldi,na.rm=T))
    info <- plyr::join(info,x,by="synaflokkur")
  } else {
    info$n.lengths <- 0
  }
  
  # For otoliths some shitmix is done
  # Include samples from other gears within this period and region
  id.other.gear <- stations$synis.id[stations$region %in% area &
                                     stations$period %in% period &
                                     stations$index != metier]
  ag.other.gear <- ages[!is.na(match(ages$synis.id,id.other.gear)),]
  ag.other.gear$fjoldi <- weight1
  
  # Include ALL otoliths from all areas and all gear with very low weight
  ag.all <- ages
  ag.all <- weight2
  
  ag <- rbind(ag,ag.other.gear,ag.all)
  
  
  keys <- MakeAlk(ag,1,kynth=F,lengd=LE,aldur=ALDUR,Stodvar=st,FilterAldurLengd=F)
  res <- MakeLdist(1,lengd=LE,Stodvar=st,lengdir=le,lengd.thyngd.data=cond,talid=F,afli=catch)
  
  
  res <- Calc.fj(keys,res)
  res$info <- info
  return(res)
}

#' @title Calculates total catch at age from catch at age by metier
#' 
#' @description XXX
#' 
#' @export
#' 
#' @param dat A list generated by the function calc_catch_at_age_by_metier that
#' contains the catch at age by each metier.
#' @param ALDUR A vector of the age classes over which the catch at age should be
#' summed over
#' @param landings An atomic vector containing the total annual landings. Used to
#' scale the catch in numbers. 
calc_catch_at_age <- function(dat,ALDUR,landings) {
  oC <- dat[[1]]$FjPerAldur 
  for(i in 2:length(dat)) {
    oC <- oC + dat[[i]]$FjPerAldur
  }
  tmp <- dat[[1]] 
  for(i in 2:length(dat)) tmp <- rbind.alk1(tmp, dat[[i]]) 
  wt <- tmp$BiomassPerAldur/apply(tmp$FjPerAldur,2,sum)
  res <- data.frame(age=c(ALDUR),fj=c(oC),wt=c(wt),bio=c(tmp$BiomassPerAldur))
  #totcatch <- sum(wts$bormicon)
  if(missing(landings))
  {
    r <- 1
  } else {
    r <- landings/sum(res$bio/1e3)
  }
  res$fj <- res$fj*r
  res$bio <- res$bio*r
  res$prosentno <- res$fj/sum(res$fj)*100
  res$prosentwt <- res$bio/sum(res$bio)*100
  res$fj <- round(res$fj,2)
  res$wt <- round(res$wt)
  res$bio <- round(res$bio/1000,1)
  res$prosentno <- round(res$prosentno,2)
  res$prosentwt <- round(res$prosentwt,2)
  return(res)
}

#' @title Obtain input data for catch-at-age calculation
#' 
#' @description The function reads in the input data, either from the data.frames
#' in the fjolst-package or from the Oracle database and returns a list with three
#' data.frames containing stations, lengths and otoliths.
#' 
#' The data returned are filtered given the specification in the input. E.g. if
#' one were only interested in compiling the catch at age for Bormicon areas 1 and
#' 2 the Region data.frame could be specified as Region = data.frame(area=c(1,2),a=c(1,1)).
#' 
#' Each data.frame of the returned data.frame has a column named index that specifies the metier (e.g. v1s1t1).
#'  
#' @export
#' 
#' @param Year Year
#' @param Species Species code
#' @param Gear data.frame containg gear code in the station table (column name vf)
#' and metier specifications (v) for the corresponding gear.
#' @param Region data.frame containing bormicon area number (column name area) and
#' and metier area specifications (column name a). Note that this is a devation from
#' the original PAX specification for areas, this being based on statistical rectangles.
#' @param Period data.frame containing months( column name month) and metier specifications (column t)
#' @param synaflokkur Numerical vector. Containing sample class limit the catch at age
#' calculation is based on.
#' @param Oracle A boolean flag, if FALSE (default) the data will be obtained from the
#' data.frame in fjolst, if TRUE (not implemented yet) the data will be read from the MRI Oracle data
#' base (requires network connection).
#' 
#' @examples 
#' # Use only longline and gill net and create one gear metier
#' Gear <- data.frame(vf=c(1,2),v=c(1,1))
#' # Allocate bormicon area to two metier regions (Northwest and Southwest regions)
#' Region <- data.frame(area=c(1:16),a=c(1,rep(2,8),1,1,rep(2,5)))
#' # One time period
#' Period <- data.frame(month=c(1:12),t=rep(1,12))
#' require(fjolst) # Need to load fjolst to access the data
#' samples <- read_pax_data(Year=2014,Species=1,Gear=Gear,Region=Region,Period=Period,synaflokkur=c(2))
#' unique(samples$stodvar$index)

read_pax_data <- function(Year,Species,Gear,Region,Period,synaflokkur,
                          Oracle=FALSE) {
  
  stodvar <- fjolst::lesa.stodvar(ar = Year, veidarfaeri = Gear$vf,oracle=Oracle)

  if(!missing(synaflokkur)) {
    stodvar <- stodvar[stodvar$synaflokkur %in% synaflokkur,]
  }
  
  #inside.reg.bcbreytt is in StdHBlib includes shallow water samples else ignored.
  # NOTE: If the data is taken from the data.frame in package fjolst (Oracle=FALSE)
  #       the function below returns the original data intact
  stodvar <- geo::inside.reg.bc(stodvar)

  stodvar <- stodvar[stodvar$area %in% Region$area,]
  
  tmp <- stodvar[,c("synis.id","veidarfaeri")]
  tmp <- plyr::mapvalues(tmp$veidarfaeri,from = Gear$vf, to=Gear$v, warn_missing=FALSE)
  
  # Create metier shortcode
  stodvar$gear <- plyr::mapvalues(stodvar$veidarfaeri, from=Gear$vf, to=Gear$v, warn_missing=FALSE)
  stodvar$region <- plyr::mapvalues(stodvar$area, from=Region$area, to=Region$a,warn_missing=FALSE)
  stodvar$period <- plyr::mapvalues(stodvar$man, from=Period$month, to=Period$t,warn_missing=FALSE)
  
  # The metier index
  stodvar$index <- paste("v",stodvar$gear,"s",stodvar$region,"t",stodvar$period,sep="", oracle=Oracle)
  
  kvarnir <- fjolst::lesa.kvarnir(stodvar$synis.id, Species, c("kyn", "kynthroski","slaegt","oslaegt"), oracle=Oracle)

  kvarnir <- kvarnir[!is.na(kvarnir$aldur),  ]
  kvarnir$fjoldi <- 1
  kvarnir <- plyr::join(kvarnir,stodvar[,c("synis.id","index","synaflokkur")],"synis.id")
  
  # Ekki nota lengdir úr netaralli
  lengdir_synis.id <- stodvar$synis.id[stodvar$synaflokkur != 34]

  lengdir <- fjolst::lesa.lengdir(lengdir_synis.id, Species, oracle=Oracle)
  lengdir <- plyr::join(lengdir,stodvar[,c("synis.id","index","synaflokkur")],"synis.id")

  
  
  stodvar <- stodvar[!is.na(match(stodvar$synis.id,c(lengdir$synis.id,kvarnir$synis.id))),]
  
  return(list(stodvar=stodvar,lengdir=lengdir,kvarnir=kvarnir))
}